// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: razpravljalnica.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST         OpType = 0 // add a message to a topic
	OpType_OP_LIKE         OpType = 1 // like a message
	OpType_OP_DELETE       OpType = 2 // delete a message
	OpType_OP_UPDATE       OpType = 3 // update a message
	OpType_OP_CREATE_USER  OpType = 4 // create a user
	OpType_OP_CREATE_TOPIC OpType = 5 // create a topic
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
		2: "OP_DELETE",
		3: "OP_UPDATE",
		4: "OP_CREATE_USER",
		5: "OP_CREATE_TOPIC",
	}
	OpType_value = map[string]int32{
		"OP_POST":         0,
		"OP_LIKE":         1,
		"OP_DELETE":       2,
		"OP_UPDATE":       3,
		"OP_CREATE_USER":  4,
		"OP_CREATE_TOPIC": 5,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_razpravljalnica_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_razpravljalnica_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

type RaftCommandType int32

const (
	RaftCommandType_OP_REGISTER   RaftCommandType = 0
	RaftCommandType_OP_UNREGISTER RaftCommandType = 1
	RaftCommandType_OP_HEARTBEAT  RaftCommandType = 2
	RaftCommandType_OP_SUBSCRIBE  RaftCommandType = 3
)

// Enum value maps for RaftCommandType.
var (
	RaftCommandType_name = map[int32]string{
		0: "OP_REGISTER",
		1: "OP_UNREGISTER",
		2: "OP_HEARTBEAT",
		3: "OP_SUBSCRIBE",
	}
	RaftCommandType_value = map[string]int32{
		"OP_REGISTER":   0,
		"OP_UNREGISTER": 1,
		"OP_HEARTBEAT":  2,
		"OP_SUBSCRIBE":  3,
	}
)

func (x RaftCommandType) Enum() *RaftCommandType {
	p := new(RaftCommandType)
	*p = x
	return p
}

func (x RaftCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_razpravljalnica_proto_enumTypes[1].Descriptor()
}

func (RaftCommandType) Type() protoreflect.EnumType {
	return &file_razpravljalnica_proto_enumTypes[1]
}

func (x RaftCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftCommandType.Descriptor instead.
func (RaftCommandType) EnumDescriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

// //////////////////////////////////////////////////////////////////////////////
// Basic data types
// //////////////////////////////////////////////////////////////////////////////
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_razpravljalnica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_razpravljalnica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_razpravljalnica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who liked the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_razpravljalnica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_razpravljalnica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{7}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *DeleteMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` // new text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *UpdateMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who posted the like
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{10}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_razpravljalnica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{11}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message (0 from beggining)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // max number of messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{12}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_razpravljalnica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{13}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // token generated by the head used to authorize the subscription
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeTopicRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // repeated int64 topic_id = 2; // (not needed here, probably?)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // subscription token to be presented to the returned node
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_razpravljalnica_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{16}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // monotonically increasing event number
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`                   // type of event
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"` // timestamp of the event
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_razpravljalnica_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{17}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_razpravljalnica_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{19}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterNodeRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type NeighborsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predecessor   *NodeInfo              `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"` // nil means no predecessor (HEAD)
	Successor     *NodeInfo              `protobuf:"bytes,2,opt,name=successor,proto3" json:"successor,omitempty"`     // nil means no successor (TAIL)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborsInfo) Reset() {
	*x = NeighborsInfo{}
	mi := &file_razpravljalnica_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborsInfo) ProtoMessage() {}

func (x *NeighborsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborsInfo.ProtoReflect.Descriptor instead.
func (*NeighborsInfo) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{21}
}

func (x *NeighborsInfo) GetPredecessor() *NodeInfo {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

func (x *NeighborsInfo) GetSuccessor() *NodeInfo {
	if x != nil {
		return x.Successor
	}
	return nil
}

// Wrap this into a seperate message to allow for nil NodeInfo values
type NodeInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoMessage) Reset() {
	*x = NodeInfoMessage{}
	mi := &file_razpravljalnica_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoMessage) ProtoMessage() {}

func (x *NodeInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoMessage.ProtoReflect.Descriptor instead.
func (*NodeInfoMessage) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{22}
}

func (x *NodeInfoMessage) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type AddSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // token to be used when opening the subscription
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddSubscriptionResponse) Reset() {
	*x = AddSubscriptionResponse{}
	mi := &file_razpravljalnica_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionResponse) ProtoMessage() {}

func (x *AddSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*AddSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{23}
}

func (x *AddSubscriptionResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type RaftCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            RaftCommandType        `protobuf:"varint,1,opt,name=op,proto3,enum=razpravljalnica.RaftCommandType" json:"op,omitempty"`
	Node          *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCommand) Reset() {
	*x = RaftCommand{}
	mi := &file_razpravljalnica_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCommand) ProtoMessage() {}

func (x *RaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCommand.ProtoReflect.Descriptor instead.
func (*RaftCommand) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{24}
}

func (x *RaftCommand) GetOp() RaftCommandType {
	if x != nil {
		return x.Op
	}
	return RaftCommandType_OP_REGISTER
}

func (x *RaftCommand) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RaftCommand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RaftSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nodes            map[string]*NodeInfo   `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Chain            []string               `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	LastControlIndex uint64                 `protobuf:"varint,3,opt,name=last_control_index,json=lastControlIndex,proto3" json:"last_control_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RaftSnapshot) Reset() {
	*x = RaftSnapshot{}
	mi := &file_razpravljalnica_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftSnapshot) ProtoMessage() {}

func (x *RaftSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftSnapshot.ProtoReflect.Descriptor instead.
func (*RaftSnapshot) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{25}
}

func (x *RaftSnapshot) GetNodes() map[string]*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RaftSnapshot) GetChain() []string {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *RaftSnapshot) GetLastControlIndex() uint64 {
	if x != nil {
		return x.LastControlIndex
	}
	return 0
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"`
	// Only one of the following will be set
	// TODO: Use "oneof"?
	PostMessage   *PostMessageRequest   `protobuf:"bytes,4,opt,name=post_message,json=postMessage,proto3" json:"post_message,omitempty"`       // set for OP_POST
	LikeMessage   *LikeMessageRequest   `protobuf:"bytes,5,opt,name=like_message,json=likeMessage,proto3" json:"like_message,omitempty"`       // set for OP_LIKE
	DeleteMessage *DeleteMessageRequest `protobuf:"bytes,6,opt,name=delete_message,json=deleteMessage,proto3" json:"delete_message,omitempty"` // set for OP_DELETE
	UpdateMessage *UpdateMessageRequest `protobuf:"bytes,7,opt,name=update_message,json=updateMessage,proto3" json:"update_message,omitempty"` // set for OP_UPDATE
	CreateUser    *CreateUserRequest    `protobuf:"bytes,8,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`          // set for OP_CREATE_USER
	CreateTopic   *CreateTopicRequest   `protobuf:"bytes,9,opt,name=create_topic,json=createTopic,proto3" json:"create_topic,omitempty"`       // set for OP_CREATE_TOPIC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_razpravljalnica_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{26}
}

func (x *Event) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Event) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *Event) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

func (x *Event) GetPostMessage() *PostMessageRequest {
	if x != nil {
		return x.PostMessage
	}
	return nil
}

func (x *Event) GetLikeMessage() *LikeMessageRequest {
	if x != nil {
		return x.LikeMessage
	}
	return nil
}

func (x *Event) GetDeleteMessage() *DeleteMessageRequest {
	if x != nil {
		return x.DeleteMessage
	}
	return nil
}

func (x *Event) GetUpdateMessage() *UpdateMessageRequest {
	if x != nil {
		return x.UpdateMessage
	}
	return nil
}

func (x *Event) GetCreateUser() *CreateUserRequest {
	if x != nil {
		return x.CreateUser
	}
	return nil
}

func (x *Event) GetCreateTopic() *CreateTopicRequest {
	if x != nil {
		return x.CreateTopic
	}
	return nil
}

type LastSequenceNumbersResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	LastSequenceNumber         int64                  `protobuf:"varint,1,opt,name=last_sequence_number,json=lastSequenceNumber,proto3" json:"last_sequence_number,omitempty"`
	AcknowledgedSequenceNumber int64                  `protobuf:"varint,2,opt,name=acknowledged_sequence_number,json=acknowledgedSequenceNumber,proto3" json:"acknowledged_sequence_number,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LastSequenceNumbersResponse) Reset() {
	*x = LastSequenceNumbersResponse{}
	mi := &file_razpravljalnica_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastSequenceNumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastSequenceNumbersResponse) ProtoMessage() {}

func (x *LastSequenceNumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastSequenceNumbersResponse.ProtoReflect.Descriptor instead.
func (*LastSequenceNumbersResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{27}
}

func (x *LastSequenceNumbersResponse) GetLastSequenceNumber() int64 {
	if x != nil {
		return x.LastSequenceNumber
	}
	return 0
}

func (x *LastSequenceNumbersResponse) GetAcknowledgedSequenceNumber() int64 {
	if x != nil {
		return x.AcknowledgedSequenceNumber
	}
	return 0
}

type AcknowledgeEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // sequence number of the event being acknowledged
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcknowledgeEventRequest) Reset() {
	*x = AcknowledgeEventRequest{}
	mi := &file_razpravljalnica_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeEventRequest) ProtoMessage() {}

func (x *AcknowledgeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeEventRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeEventRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_proto_rawDescGZIP(), []int{28}
}

func (x *AcknowledgeEventRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

var File_razpravljalnica_proto protoreflect.FileDescriptor

const file_razpravljalnica_proto_rawDesc = "" +
	"\n" +
	"\x15razpravljalnica.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"i\n" +
	"\x14DeleteMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"}\n" +
	"\x14UpdateMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"g\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\"m\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"2\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"r\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\xcb\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"w\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\"D\n" +
	"\x13RegisterNodeRequest\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\x85\x01\n" +
	"\rNeighborsInfo\x12;\n" +
	"\vpredecessor\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\vpredecessor\x127\n" +
	"\tsuccessor\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\tsuccessor\"@\n" +
	"\x0fNodeInfoMessage\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"B\n" +
	"\x17AddSubscriptionResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\"\xa9\x01\n" +
	"\vRaftCommand\x120\n" +
	"\x02op\x18\x01 \x01(\x0e2 .razpravljalnica.RaftCommandTypeR\x02op\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe7\x01\n" +
	"\fRaftSnapshot\x12>\n" +
	"\x05nodes\x18\x01 \x03(\v2(.razpravljalnica.RaftSnapshot.NodesEntryR\x05nodes\x12\x14\n" +
	"\x05chain\x18\x02 \x03(\tR\x05chain\x12,\n" +
	"\x12last_control_index\x18\x03 \x01(\x04R\x10lastControlIndex\x1aS\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x05value:\x028\x01\"\xc9\x04\n" +
	"\x05Event\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x125\n" +
	"\bevent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\x12F\n" +
	"\fpost_message\x18\x04 \x01(\v2#.razpravljalnica.PostMessageRequestR\vpostMessage\x12F\n" +
	"\flike_message\x18\x05 \x01(\v2#.razpravljalnica.LikeMessageRequestR\vlikeMessage\x12L\n" +
	"\x0edelete_message\x18\x06 \x01(\v2%.razpravljalnica.DeleteMessageRequestR\rdeleteMessage\x12L\n" +
	"\x0eupdate_message\x18\a \x01(\v2%.razpravljalnica.UpdateMessageRequestR\rupdateMessage\x12C\n" +
	"\vcreate_user\x18\b \x01(\v2\".razpravljalnica.CreateUserRequestR\n" +
	"createUser\x12F\n" +
	"\fcreate_topic\x18\t \x01(\v2#.razpravljalnica.CreateTopicRequestR\vcreateTopic\"\x91\x01\n" +
	"\x1bLastSequenceNumbersResponse\x120\n" +
	"\x14last_sequence_number\x18\x01 \x01(\x03R\x12lastSequenceNumber\x12@\n" +
	"\x1cacknowledged_sequence_number\x18\x02 \x01(\x03R\x1aacknowledgedSequenceNumber\"B\n" +
	"\x17AcknowledgeEventRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber*i\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02\x12\r\n" +
	"\tOP_UPDATE\x10\x03\x12\x12\n" +
	"\x0eOP_CREATE_USER\x10\x04\x12\x13\n" +
	"\x0fOP_CREATE_TOPIC\x10\x05*Y\n" +
	"\x0fRaftCommandType\x12\x0f\n" +
	"\vOP_REGISTER\x10\x00\x12\x11\n" +
	"\rOP_UNREGISTER\x10\x01\x12\x10\n" +
	"\fOP_HEARTBEAT\x10\x02\x12\x10\n" +
	"\fOP_SUBSCRIBE\x10\x032\xe7\x03\n" +
	"\x12MessageBoardWrites\x12G\n" +
	"\n" +
	"CreateUser\x12\".razpravljalnica.CreateUserRequest\x1a\x15.razpravljalnica.User\x12J\n" +
	"\vCreateTopic\x12#.razpravljalnica.CreateTopicRequest\x1a\x16.razpravljalnica.Topic\x12L\n" +
	"\vPostMessage\x12#.razpravljalnica.PostMessageRequest\x1a\x18.razpravljalnica.Message\x12P\n" +
	"\rUpdateMessage\x12%.razpravljalnica.UpdateMessageRequest\x1a\x18.razpravljalnica.Message\x12N\n" +
	"\rDeleteMessage\x12%.razpravljalnica.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vLikeMessage\x12#.razpravljalnica.LikeMessageRequest\x1a\x18.razpravljalnica.Message2\xfb\x01\n" +
	"\x11MessageBoardReads\x12I\n" +
	"\n" +
	"ListTopics\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ListTopicsResponse\x12A\n" +
	"\aGetUser\x12\x1f.razpravljalnica.GetUserRequest\x1a\x15.razpravljalnica.User\x12X\n" +
	"\vGetMessages\x12#.razpravljalnica.GetMessagesRequest\x1a$.razpravljalnica.GetMessagesResponse2v\n" +
	"\x19MessageBoardSubscriptions\x12Y\n" +
	"\x0eSubscribeTopic\x12&.razpravljalnica.SubscribeTopicRequest\x1a\x1d.razpravljalnica.MessageEvent0\x012\xd2\x01\n" +
	"\x0fClientDiscovery\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12j\n" +
	"\x13GetSubscriptionNode\x12(.razpravljalnica.SubscriptionNodeRequest\x1a).razpravljalnica.SubscriptionNodeResponse2\xde\x01\n" +
	"\fControlPlane\x12>\n" +
	"\tHeartbeat\x12\x19.razpravljalnica.NodeInfo\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fRegisterNode\x12\x19.razpravljalnica.NodeInfo\x1a\x1e.razpravljalnica.NeighborsInfo\x12C\n" +
	"\x0eUnregisterNode\x12\x19.razpravljalnica.NodeInfo\x1a\x16.google.protobuf.Empty2\x90\x02\n" +
	"\n" +
	"NodeUpdate\x12J\n" +
	"\x0eSetPredecessor\x12 .razpravljalnica.NodeInfoMessage\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\fSetSuccessor\x12 .razpravljalnica.NodeInfoMessage\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x16AddSubscriptionRequest\x12(.razpravljalnica.SubscriptionNodeRequest\x1a(.razpravljalnica.AddSubscriptionResponse2\x8a\x02\n" +
	"\x10ChainReplication\x12@\n" +
	"\x0eReplicateEvent\x12\x16.razpravljalnica.Event\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x10AcknowledgeEvent\x12(.razpravljalnica.AcknowledgeEventRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x16GetLastSequenceNumbers\x12\x16.google.protobuf.Empty\x1a,.razpravljalnica.LastSequenceNumbersResponseB\x12Z\x10/razpravljalnicab\x06proto3"

var (
	file_razpravljalnica_proto_rawDescOnce sync.Once
	file_razpravljalnica_proto_rawDescData []byte
)

func file_razpravljalnica_proto_rawDescGZIP() []byte {
	file_razpravljalnica_proto_rawDescOnce.Do(func() {
		file_razpravljalnica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_razpravljalnica_proto_rawDesc), len(file_razpravljalnica_proto_rawDesc)))
	})
	return file_razpravljalnica_proto_rawDescData
}

var file_razpravljalnica_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_razpravljalnica_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_razpravljalnica_proto_goTypes = []any{
	(OpType)(0),                         // 0: razpravljalnica.OpType
	(RaftCommandType)(0),                // 1: razpravljalnica.RaftCommandType
	(*User)(nil),                        // 2: razpravljalnica.User
	(*Topic)(nil),                       // 3: razpravljalnica.Topic
	(*Message)(nil),                     // 4: razpravljalnica.Message
	(*Like)(nil),                        // 5: razpravljalnica.Like
	(*NodeInfo)(nil),                    // 6: razpravljalnica.NodeInfo
	(*CreateUserRequest)(nil),           // 7: razpravljalnica.CreateUserRequest
	(*CreateTopicRequest)(nil),          // 8: razpravljalnica.CreateTopicRequest
	(*PostMessageRequest)(nil),          // 9: razpravljalnica.PostMessageRequest
	(*DeleteMessageRequest)(nil),        // 10: razpravljalnica.DeleteMessageRequest
	(*UpdateMessageRequest)(nil),        // 11: razpravljalnica.UpdateMessageRequest
	(*LikeMessageRequest)(nil),          // 12: razpravljalnica.LikeMessageRequest
	(*ListTopicsResponse)(nil),          // 13: razpravljalnica.ListTopicsResponse
	(*GetMessagesRequest)(nil),          // 14: razpravljalnica.GetMessagesRequest
	(*GetMessagesResponse)(nil),         // 15: razpravljalnica.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),       // 16: razpravljalnica.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),     // 17: razpravljalnica.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil),    // 18: razpravljalnica.SubscriptionNodeResponse
	(*MessageEvent)(nil),                // 19: razpravljalnica.MessageEvent
	(*GetUserRequest)(nil),              // 20: razpravljalnica.GetUserRequest
	(*GetClusterStateResponse)(nil),     // 21: razpravljalnica.GetClusterStateResponse
	(*RegisterNodeRequest)(nil),         // 22: razpravljalnica.RegisterNodeRequest
	(*NeighborsInfo)(nil),               // 23: razpravljalnica.NeighborsInfo
	(*NodeInfoMessage)(nil),             // 24: razpravljalnica.NodeInfoMessage
	(*AddSubscriptionResponse)(nil),     // 25: razpravljalnica.AddSubscriptionResponse
	(*RaftCommand)(nil),                 // 26: razpravljalnica.RaftCommand
	(*RaftSnapshot)(nil),                // 27: razpravljalnica.RaftSnapshot
	(*Event)(nil),                       // 28: razpravljalnica.Event
	(*LastSequenceNumbersResponse)(nil), // 29: razpravljalnica.LastSequenceNumbersResponse
	(*AcknowledgeEventRequest)(nil),     // 30: razpravljalnica.AcknowledgeEventRequest
	nil,                                 // 31: razpravljalnica.RaftSnapshot.NodesEntry
	(*timestamppb.Timestamp)(nil),       // 32: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 33: google.protobuf.Empty
}
var file_razpravljalnica_proto_depIdxs = []int32{
	32, // 0: razpravljalnica.Message.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: razpravljalnica.ListTopicsResponse.topics:type_name -> razpravljalnica.Topic
	4,  // 2: razpravljalnica.GetMessagesResponse.messages:type_name -> razpravljalnica.Message
	6,  // 3: razpravljalnica.SubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	0,  // 4: razpravljalnica.MessageEvent.op:type_name -> razpravljalnica.OpType
	4,  // 5: razpravljalnica.MessageEvent.message:type_name -> razpravljalnica.Message
	32, // 6: razpravljalnica.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	6,  // 7: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	6,  // 8: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	6,  // 9: razpravljalnica.RegisterNodeRequest.node:type_name -> razpravljalnica.NodeInfo
	6,  // 10: razpravljalnica.NeighborsInfo.predecessor:type_name -> razpravljalnica.NodeInfo
	6,  // 11: razpravljalnica.NeighborsInfo.successor:type_name -> razpravljalnica.NodeInfo
	6,  // 12: razpravljalnica.NodeInfoMessage.node:type_name -> razpravljalnica.NodeInfo
	1,  // 13: razpravljalnica.RaftCommand.op:type_name -> razpravljalnica.RaftCommandType
	6,  // 14: razpravljalnica.RaftCommand.node:type_name -> razpravljalnica.NodeInfo
	32, // 15: razpravljalnica.RaftCommand.created_at:type_name -> google.protobuf.Timestamp
	31, // 16: razpravljalnica.RaftSnapshot.nodes:type_name -> razpravljalnica.RaftSnapshot.NodesEntry
	0,  // 17: razpravljalnica.Event.op:type_name -> razpravljalnica.OpType
	32, // 18: razpravljalnica.Event.event_at:type_name -> google.protobuf.Timestamp
	9,  // 19: razpravljalnica.Event.post_message:type_name -> razpravljalnica.PostMessageRequest
	12, // 20: razpravljalnica.Event.like_message:type_name -> razpravljalnica.LikeMessageRequest
	10, // 21: razpravljalnica.Event.delete_message:type_name -> razpravljalnica.DeleteMessageRequest
	11, // 22: razpravljalnica.Event.update_message:type_name -> razpravljalnica.UpdateMessageRequest
	7,  // 23: razpravljalnica.Event.create_user:type_name -> razpravljalnica.CreateUserRequest
	8,  // 24: razpravljalnica.Event.create_topic:type_name -> razpravljalnica.CreateTopicRequest
	6,  // 25: razpravljalnica.RaftSnapshot.NodesEntry.value:type_name -> razpravljalnica.NodeInfo
	7,  // 26: razpravljalnica.MessageBoardWrites.CreateUser:input_type -> razpravljalnica.CreateUserRequest
	8,  // 27: razpravljalnica.MessageBoardWrites.CreateTopic:input_type -> razpravljalnica.CreateTopicRequest
	9,  // 28: razpravljalnica.MessageBoardWrites.PostMessage:input_type -> razpravljalnica.PostMessageRequest
	11, // 29: razpravljalnica.MessageBoardWrites.UpdateMessage:input_type -> razpravljalnica.UpdateMessageRequest
	10, // 30: razpravljalnica.MessageBoardWrites.DeleteMessage:input_type -> razpravljalnica.DeleteMessageRequest
	12, // 31: razpravljalnica.MessageBoardWrites.LikeMessage:input_type -> razpravljalnica.LikeMessageRequest
	33, // 32: razpravljalnica.MessageBoardReads.ListTopics:input_type -> google.protobuf.Empty
	20, // 33: razpravljalnica.MessageBoardReads.GetUser:input_type -> razpravljalnica.GetUserRequest
	14, // 34: razpravljalnica.MessageBoardReads.GetMessages:input_type -> razpravljalnica.GetMessagesRequest
	16, // 35: razpravljalnica.MessageBoardSubscriptions.SubscribeTopic:input_type -> razpravljalnica.SubscribeTopicRequest
	33, // 36: razpravljalnica.ClientDiscovery.GetClusterState:input_type -> google.protobuf.Empty
	17, // 37: razpravljalnica.ClientDiscovery.GetSubscriptionNode:input_type -> razpravljalnica.SubscriptionNodeRequest
	6,  // 38: razpravljalnica.ControlPlane.Heartbeat:input_type -> razpravljalnica.NodeInfo
	6,  // 39: razpravljalnica.ControlPlane.RegisterNode:input_type -> razpravljalnica.NodeInfo
	6,  // 40: razpravljalnica.ControlPlane.UnregisterNode:input_type -> razpravljalnica.NodeInfo
	24, // 41: razpravljalnica.NodeUpdate.SetPredecessor:input_type -> razpravljalnica.NodeInfoMessage
	24, // 42: razpravljalnica.NodeUpdate.SetSuccessor:input_type -> razpravljalnica.NodeInfoMessage
	17, // 43: razpravljalnica.NodeUpdate.AddSubscriptionRequest:input_type -> razpravljalnica.SubscriptionNodeRequest
	28, // 44: razpravljalnica.ChainReplication.ReplicateEvent:input_type -> razpravljalnica.Event
	30, // 45: razpravljalnica.ChainReplication.AcknowledgeEvent:input_type -> razpravljalnica.AcknowledgeEventRequest
	33, // 46: razpravljalnica.ChainReplication.GetLastSequenceNumbers:input_type -> google.protobuf.Empty
	2,  // 47: razpravljalnica.MessageBoardWrites.CreateUser:output_type -> razpravljalnica.User
	3,  // 48: razpravljalnica.MessageBoardWrites.CreateTopic:output_type -> razpravljalnica.Topic
	4,  // 49: razpravljalnica.MessageBoardWrites.PostMessage:output_type -> razpravljalnica.Message
	4,  // 50: razpravljalnica.MessageBoardWrites.UpdateMessage:output_type -> razpravljalnica.Message
	33, // 51: razpravljalnica.MessageBoardWrites.DeleteMessage:output_type -> google.protobuf.Empty
	4,  // 52: razpravljalnica.MessageBoardWrites.LikeMessage:output_type -> razpravljalnica.Message
	13, // 53: razpravljalnica.MessageBoardReads.ListTopics:output_type -> razpravljalnica.ListTopicsResponse
	2,  // 54: razpravljalnica.MessageBoardReads.GetUser:output_type -> razpravljalnica.User
	15, // 55: razpravljalnica.MessageBoardReads.GetMessages:output_type -> razpravljalnica.GetMessagesResponse
	19, // 56: razpravljalnica.MessageBoardSubscriptions.SubscribeTopic:output_type -> razpravljalnica.MessageEvent
	21, // 57: razpravljalnica.ClientDiscovery.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	18, // 58: razpravljalnica.ClientDiscovery.GetSubscriptionNode:output_type -> razpravljalnica.SubscriptionNodeResponse
	33, // 59: razpravljalnica.ControlPlane.Heartbeat:output_type -> google.protobuf.Empty
	23, // 60: razpravljalnica.ControlPlane.RegisterNode:output_type -> razpravljalnica.NeighborsInfo
	33, // 61: razpravljalnica.ControlPlane.UnregisterNode:output_type -> google.protobuf.Empty
	33, // 62: razpravljalnica.NodeUpdate.SetPredecessor:output_type -> google.protobuf.Empty
	33, // 63: razpravljalnica.NodeUpdate.SetSuccessor:output_type -> google.protobuf.Empty
	25, // 64: razpravljalnica.NodeUpdate.AddSubscriptionRequest:output_type -> razpravljalnica.AddSubscriptionResponse
	33, // 65: razpravljalnica.ChainReplication.ReplicateEvent:output_type -> google.protobuf.Empty
	33, // 66: razpravljalnica.ChainReplication.AcknowledgeEvent:output_type -> google.protobuf.Empty
	29, // 67: razpravljalnica.ChainReplication.GetLastSequenceNumbers:output_type -> razpravljalnica.LastSequenceNumbersResponse
	47, // [47:68] is the sub-list for method output_type
	26, // [26:47] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_razpravljalnica_proto_init() }
func file_razpravljalnica_proto_init() {
	if File_razpravljalnica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_razpravljalnica_proto_rawDesc), len(file_razpravljalnica_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_razpravljalnica_proto_goTypes,
		DependencyIndexes: file_razpravljalnica_proto_depIdxs,
		EnumInfos:         file_razpravljalnica_proto_enumTypes,
		MessageInfos:      file_razpravljalnica_proto_msgTypes,
	}.Build()
	File_razpravljalnica_proto = out.File
	file_razpravljalnica_proto_goTypes = nil
	file_razpravljalnica_proto_depIdxs = nil
}
