// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: razpravljalnica.proto

package razpravljalnica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageBoardWrites_CreateUser_FullMethodName    = "/razpravljalnica.MessageBoardWrites/CreateUser"
	MessageBoardWrites_CreateTopic_FullMethodName   = "/razpravljalnica.MessageBoardWrites/CreateTopic"
	MessageBoardWrites_PostMessage_FullMethodName   = "/razpravljalnica.MessageBoardWrites/PostMessage"
	MessageBoardWrites_UpdateMessage_FullMethodName = "/razpravljalnica.MessageBoardWrites/UpdateMessage"
	MessageBoardWrites_DeleteMessage_FullMethodName = "/razpravljalnica.MessageBoardWrites/DeleteMessage"
	MessageBoardWrites_LikeMessage_FullMethodName   = "/razpravljalnica.MessageBoardWrites/LikeMessage"
)

// MessageBoardWritesClient is the client API for MessageBoardWrites service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Writes (only to head)
type MessageBoardWritesClient interface {
	// Creates a new user and assigns it an id
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Creates a new topic to which users can post messages
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Topic, error)
	// Post a message to a topic; Succeed only if the User and the Topic exist in the database.
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*Message, error)
	// Update an existing message. Allowed only for the user who posted the message.
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	// Delete an existing message. Allowed only for the user who posted the message.
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Like an existing message. Return the message with the new number of likes.
	LikeMessage(ctx context.Context, in *LikeMessageRequest, opts ...grpc.CallOption) (*Message, error)
}

type messageBoardWritesClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBoardWritesClient(cc grpc.ClientConnInterface) MessageBoardWritesClient {
	return &messageBoardWritesClient{cc}
}

func (c *messageBoardWritesClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, MessageBoardWrites_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardWritesClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Topic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Topic)
	err := c.cc.Invoke(ctx, MessageBoardWrites_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardWritesClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoardWrites_PostMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardWritesClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoardWrites_UpdateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardWritesClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageBoardWrites_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardWritesClient) LikeMessage(ctx context.Context, in *LikeMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoardWrites_LikeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBoardWritesServer is the server API for MessageBoardWrites service.
// All implementations must embed UnimplementedMessageBoardWritesServer
// for forward compatibility.
//
// Writes (only to head)
type MessageBoardWritesServer interface {
	// Creates a new user and assigns it an id
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	// Creates a new topic to which users can post messages
	CreateTopic(context.Context, *CreateTopicRequest) (*Topic, error)
	// Post a message to a topic; Succeed only if the User and the Topic exist in the database.
	PostMessage(context.Context, *PostMessageRequest) (*Message, error)
	// Update an existing message. Allowed only for the user who posted the message.
	UpdateMessage(context.Context, *UpdateMessageRequest) (*Message, error)
	// Delete an existing message. Allowed only for the user who posted the message.
	DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error)
	// Like an existing message. Return the message with the new number of likes.
	LikeMessage(context.Context, *LikeMessageRequest) (*Message, error)
	mustEmbedUnimplementedMessageBoardWritesServer()
}

// UnimplementedMessageBoardWritesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageBoardWritesServer struct{}

func (UnimplementedMessageBoardWritesServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMessageBoardWritesServer) CreateTopic(context.Context, *CreateTopicRequest) (*Topic, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedMessageBoardWritesServer) PostMessage(context.Context, *PostMessageRequest) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedMessageBoardWritesServer) UpdateMessage(context.Context, *UpdateMessageRequest) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMessage not implemented")
}
func (UnimplementedMessageBoardWritesServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMessageBoardWritesServer) LikeMessage(context.Context, *LikeMessageRequest) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeMessage not implemented")
}
func (UnimplementedMessageBoardWritesServer) mustEmbedUnimplementedMessageBoardWritesServer() {}
func (UnimplementedMessageBoardWritesServer) testEmbeddedByValue()                            {}

// UnsafeMessageBoardWritesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBoardWritesServer will
// result in compilation errors.
type UnsafeMessageBoardWritesServer interface {
	mustEmbedUnimplementedMessageBoardWritesServer()
}

func RegisterMessageBoardWritesServer(s grpc.ServiceRegistrar, srv MessageBoardWritesServer) {
	// If the following call panics, it indicates UnimplementedMessageBoardWritesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageBoardWrites_ServiceDesc, srv)
}

func _MessageBoardWrites_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardWritesServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardWrites_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardWritesServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardWrites_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardWritesServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardWrites_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardWritesServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardWrites_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardWritesServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardWrites_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardWritesServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardWrites_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardWritesServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardWrites_UpdateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardWritesServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardWrites_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardWritesServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardWrites_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardWritesServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardWrites_LikeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardWritesServer).LikeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardWrites_LikeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardWritesServer).LikeMessage(ctx, req.(*LikeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageBoardWrites_ServiceDesc is the grpc.ServiceDesc for MessageBoardWrites service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBoardWrites_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.MessageBoardWrites",
	HandlerType: (*MessageBoardWritesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MessageBoardWrites_CreateUser_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _MessageBoardWrites_CreateTopic_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _MessageBoardWrites_PostMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _MessageBoardWrites_UpdateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _MessageBoardWrites_DeleteMessage_Handler,
		},
		{
			MethodName: "LikeMessage",
			Handler:    _MessageBoardWrites_LikeMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "razpravljalnica.proto",
}

const (
	MessageBoardReads_ListTopics_FullMethodName  = "/razpravljalnica.MessageBoardReads/ListTopics"
	MessageBoardReads_GetUser_FullMethodName     = "/razpravljalnica.MessageBoardReads/GetUser"
	MessageBoardReads_GetMessages_FullMethodName = "/razpravljalnica.MessageBoardReads/GetMessages"
)

// MessageBoardReadsClient is the client API for MessageBoardReads service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Reads go to the tail node
type MessageBoardReadsClient interface {
	// Returns all the topics
	ListTopics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	// NOTE: Add method GetUsers or attach name to message in order to obtain user names.
	// Currently, there is no way for the client to display user names, only user IDs
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// Returns messages in a topic
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type messageBoardReadsClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBoardReadsClient(cc grpc.ClientConnInterface) MessageBoardReadsClient {
	return &messageBoardReadsClient{cc}
}

func (c *messageBoardReadsClient) ListTopics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, MessageBoardReads_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardReadsClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, MessageBoardReads_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardReadsClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, MessageBoardReads_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBoardReadsServer is the server API for MessageBoardReads service.
// All implementations must embed UnimplementedMessageBoardReadsServer
// for forward compatibility.
//
// Reads go to the tail node
type MessageBoardReadsServer interface {
	// Returns all the topics
	ListTopics(context.Context, *emptypb.Empty) (*ListTopicsResponse, error)
	// NOTE: Add method GetUsers or attach name to message in order to obtain user names.
	// Currently, there is no way for the client to display user names, only user IDs
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// Returns messages in a topic
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	mustEmbedUnimplementedMessageBoardReadsServer()
}

// UnimplementedMessageBoardReadsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageBoardReadsServer struct{}

func (UnimplementedMessageBoardReadsServer) ListTopics(context.Context, *emptypb.Empty) (*ListTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedMessageBoardReadsServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedMessageBoardReadsServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedMessageBoardReadsServer) mustEmbedUnimplementedMessageBoardReadsServer() {}
func (UnimplementedMessageBoardReadsServer) testEmbeddedByValue()                           {}

// UnsafeMessageBoardReadsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBoardReadsServer will
// result in compilation errors.
type UnsafeMessageBoardReadsServer interface {
	mustEmbedUnimplementedMessageBoardReadsServer()
}

func RegisterMessageBoardReadsServer(s grpc.ServiceRegistrar, srv MessageBoardReadsServer) {
	// If the following call panics, it indicates UnimplementedMessageBoardReadsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageBoardReads_ServiceDesc, srv)
}

func _MessageBoardReads_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardReadsServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardReads_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardReadsServer).ListTopics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardReads_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardReadsServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardReads_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardReadsServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoardReads_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardReadsServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardReads_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardReadsServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageBoardReads_ServiceDesc is the grpc.ServiceDesc for MessageBoardReads service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBoardReads_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.MessageBoardReads",
	HandlerType: (*MessageBoardReadsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTopics",
			Handler:    _MessageBoardReads_ListTopics_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _MessageBoardReads_GetUser_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _MessageBoardReads_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "razpravljalnica.proto",
}

const (
	MessageBoardSubscriptions_SubscribeTopic_FullMethodName      = "/razpravljalnica.MessageBoardSubscriptions/SubscribeTopic"
	MessageBoardSubscriptions_GetSubscriptionNode_FullMethodName = "/razpravljalnica.MessageBoardSubscriptions/GetSubscriptionNode"
)

// MessageBoardSubscriptionsClient is the client API for MessageBoardSubscriptions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Subscriptions; goes to the node (in the middle of the chain) returned by head
type MessageBoardSubscriptionsClient interface {
	// Subscribe to topics; goes to the node returned by head
	SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageEvent], error)
	// Request a node to which a subscription can be opened.
	GetSubscriptionNode(ctx context.Context, in *SubscriptionNodeRequest, opts ...grpc.CallOption) (*SubscriptionNodeResponse, error)
}

type messageBoardSubscriptionsClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBoardSubscriptionsClient(cc grpc.ClientConnInterface) MessageBoardSubscriptionsClient {
	return &messageBoardSubscriptionsClient{cc}
}

func (c *messageBoardSubscriptionsClient) SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageBoardSubscriptions_ServiceDesc.Streams[0], MessageBoardSubscriptions_SubscribeTopic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTopicRequest, MessageEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageBoardSubscriptions_SubscribeTopicClient = grpc.ServerStreamingClient[MessageEvent]

func (c *messageBoardSubscriptionsClient) GetSubscriptionNode(ctx context.Context, in *SubscriptionNodeRequest, opts ...grpc.CallOption) (*SubscriptionNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionNodeResponse)
	err := c.cc.Invoke(ctx, MessageBoardSubscriptions_GetSubscriptionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBoardSubscriptionsServer is the server API for MessageBoardSubscriptions service.
// All implementations must embed UnimplementedMessageBoardSubscriptionsServer
// for forward compatibility.
//
// Subscriptions; goes to the node (in the middle of the chain) returned by head
type MessageBoardSubscriptionsServer interface {
	// Subscribe to topics; goes to the node returned by head
	SubscribeTopic(*SubscribeTopicRequest, grpc.ServerStreamingServer[MessageEvent]) error
	// Request a node to which a subscription can be opened.
	GetSubscriptionNode(context.Context, *SubscriptionNodeRequest) (*SubscriptionNodeResponse, error)
	mustEmbedUnimplementedMessageBoardSubscriptionsServer()
}

// UnimplementedMessageBoardSubscriptionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageBoardSubscriptionsServer struct{}

func (UnimplementedMessageBoardSubscriptionsServer) SubscribeTopic(*SubscribeTopicRequest, grpc.ServerStreamingServer[MessageEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTopic not implemented")
}
func (UnimplementedMessageBoardSubscriptionsServer) GetSubscriptionNode(context.Context, *SubscriptionNodeRequest) (*SubscriptionNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptionNode not implemented")
}
func (UnimplementedMessageBoardSubscriptionsServer) mustEmbedUnimplementedMessageBoardSubscriptionsServer() {
}
func (UnimplementedMessageBoardSubscriptionsServer) testEmbeddedByValue() {}

// UnsafeMessageBoardSubscriptionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBoardSubscriptionsServer will
// result in compilation errors.
type UnsafeMessageBoardSubscriptionsServer interface {
	mustEmbedUnimplementedMessageBoardSubscriptionsServer()
}

func RegisterMessageBoardSubscriptionsServer(s grpc.ServiceRegistrar, srv MessageBoardSubscriptionsServer) {
	// If the following call panics, it indicates UnimplementedMessageBoardSubscriptionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageBoardSubscriptions_ServiceDesc, srv)
}

func _MessageBoardSubscriptions_SubscribeTopic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTopicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageBoardSubscriptionsServer).SubscribeTopic(m, &grpc.GenericServerStream[SubscribeTopicRequest, MessageEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageBoardSubscriptions_SubscribeTopicServer = grpc.ServerStreamingServer[MessageEvent]

func _MessageBoardSubscriptions_GetSubscriptionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardSubscriptionsServer).GetSubscriptionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoardSubscriptions_GetSubscriptionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardSubscriptionsServer).GetSubscriptionNode(ctx, req.(*SubscriptionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageBoardSubscriptions_ServiceDesc is the grpc.ServiceDesc for MessageBoardSubscriptions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBoardSubscriptions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.MessageBoardSubscriptions",
	HandlerType: (*MessageBoardSubscriptionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriptionNode",
			Handler:    _MessageBoardSubscriptions_GetSubscriptionNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTopic",
			Handler:       _MessageBoardSubscriptions_SubscribeTopic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "razpravljalnica.proto",
}

const (
	ClientDiscovery_GetClusterState_FullMethodName = "/razpravljalnica.ClientDiscovery/GetClusterState"
)

// ClientDiscoveryClient is the client API for ClientDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API for clients
type ClientDiscoveryClient interface {
	// Get the current head and tail nodes (for the client to connect to)
	GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClusterStateResponse, error)
}

type clientDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewClientDiscoveryClient(cc grpc.ClientConnInterface) ClientDiscoveryClient {
	return &clientDiscoveryClient{cc}
}

func (c *clientDiscoveryClient) GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClusterStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStateResponse)
	err := c.cc.Invoke(ctx, ClientDiscovery_GetClusterState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientDiscoveryServer is the server API for ClientDiscovery service.
// All implementations must embed UnimplementedClientDiscoveryServer
// for forward compatibility.
//
// API for clients
type ClientDiscoveryServer interface {
	// Get the current head and tail nodes (for the client to connect to)
	GetClusterState(context.Context, *emptypb.Empty) (*GetClusterStateResponse, error)
	mustEmbedUnimplementedClientDiscoveryServer()
}

// UnimplementedClientDiscoveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientDiscoveryServer struct{}

func (UnimplementedClientDiscoveryServer) GetClusterState(context.Context, *emptypb.Empty) (*GetClusterStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterState not implemented")
}
func (UnimplementedClientDiscoveryServer) mustEmbedUnimplementedClientDiscoveryServer() {}
func (UnimplementedClientDiscoveryServer) testEmbeddedByValue()                         {}

// UnsafeClientDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientDiscoveryServer will
// result in compilation errors.
type UnsafeClientDiscoveryServer interface {
	mustEmbedUnimplementedClientDiscoveryServer()
}

func RegisterClientDiscoveryServer(s grpc.ServiceRegistrar, srv ClientDiscoveryServer) {
	// If the following call panics, it indicates UnimplementedClientDiscoveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientDiscovery_ServiceDesc, srv)
}

func _ClientDiscovery_GetClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDiscoveryServer).GetClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientDiscovery_GetClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDiscoveryServer).GetClusterState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientDiscovery_ServiceDesc is the grpc.ServiceDesc for ClientDiscovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientDiscovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.ClientDiscovery",
	HandlerType: (*ClientDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterState",
			Handler:    _ClientDiscovery_GetClusterState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "razpravljalnica.proto",
}

const (
	ControlPlane_Heartbeat_FullMethodName      = "/razpravljalnica.ControlPlane/Heartbeat"
	ControlPlane_RegisterNode_FullMethodName   = "/razpravljalnica.ControlPlane/RegisterNode"
	ControlPlane_UnregisterNode_FullMethodName = "/razpravljalnica.ControlPlane/UnregisterNode"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API for nodes to call the control plane (node -> control plane)
type ControlPlaneClient interface {
	// Heartbeat from a node to indicate it is alive
	Heartbeat(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Register a new node in the cluster
	RegisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*NeighborsInfo, error)
	// Remove an existing node from the cluster
	UnregisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RegisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*NeighborsInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeighborsInfo)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) UnregisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlPlane_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// API for nodes to call the control plane (node -> control plane)
type ControlPlaneServer interface {
	// Heartbeat from a node to indicate it is alive
	Heartbeat(context.Context, *NodeInfo) (*emptypb.Empty, error)
	// Register a new node in the cluster
	RegisterNode(context.Context, *NodeInfo) (*NeighborsInfo, error)
	// Remove an existing node from the cluster
	UnregisterNode(context.Context, *NodeInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *NodeInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) RegisterNode(context.Context, *NodeInfo) (*NeighborsInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControlPlaneServer) UnregisterNode(context.Context, *NodeInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterNode(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).UnregisterNode(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _ControlPlane_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _ControlPlane_UnregisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "razpravljalnica.proto",
}

const (
	NodeUpdate_SetPredecessor_FullMethodName = "/razpravljalnica.NodeUpdate/SetPredecessor"
	NodeUpdate_SetSuccessor_FullMethodName   = "/razpravljalnica.NodeUpdate/SetSuccessor"
)

// NodeUpdateClient is the client API for NodeUpdate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API for control plane to call nodes (control plane -> node)
type NodeUpdateClient interface {
	// Inform a node about its new predecessor
	SetPredecessor(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Inform a node about its new successor
	SetSuccessor(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nodeUpdateClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeUpdateClient(cc grpc.ClientConnInterface) NodeUpdateClient {
	return &nodeUpdateClient{cc}
}

func (c *nodeUpdateClient) SetPredecessor(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeUpdate_SetPredecessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeUpdateClient) SetSuccessor(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeUpdate_SetSuccessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeUpdateServer is the server API for NodeUpdate service.
// All implementations must embed UnimplementedNodeUpdateServer
// for forward compatibility.
//
// API for control plane to call nodes (control plane -> node)
type NodeUpdateServer interface {
	// Inform a node about its new predecessor
	SetPredecessor(context.Context, *NodeInfo) (*emptypb.Empty, error)
	// Inform a node about its new successor
	SetSuccessor(context.Context, *NodeInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedNodeUpdateServer()
}

// UnimplementedNodeUpdateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeUpdateServer struct{}

func (UnimplementedNodeUpdateServer) SetPredecessor(context.Context, *NodeInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPredecessor not implemented")
}
func (UnimplementedNodeUpdateServer) SetSuccessor(context.Context, *NodeInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSuccessor not implemented")
}
func (UnimplementedNodeUpdateServer) mustEmbedUnimplementedNodeUpdateServer() {}
func (UnimplementedNodeUpdateServer) testEmbeddedByValue()                    {}

// UnsafeNodeUpdateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeUpdateServer will
// result in compilation errors.
type UnsafeNodeUpdateServer interface {
	mustEmbedUnimplementedNodeUpdateServer()
}

func RegisterNodeUpdateServer(s grpc.ServiceRegistrar, srv NodeUpdateServer) {
	// If the following call panics, it indicates UnimplementedNodeUpdateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeUpdate_ServiceDesc, srv)
}

func _NodeUpdate_SetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeUpdateServer).SetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeUpdate_SetPredecessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeUpdateServer).SetPredecessor(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeUpdate_SetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeUpdateServer).SetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeUpdate_SetSuccessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeUpdateServer).SetSuccessor(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeUpdate_ServiceDesc is the grpc.ServiceDesc for NodeUpdate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeUpdate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.NodeUpdate",
	HandlerType: (*NodeUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPredecessor",
			Handler:    _NodeUpdate_SetPredecessor_Handler,
		},
		{
			MethodName: "SetSuccessor",
			Handler:    _NodeUpdate_SetSuccessor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "razpravljalnica.proto",
}

const (
	ChainReplication_ReplicateEvent_FullMethodName        = "/razpravljalnica.ChainReplication/ReplicateEvent"
	ChainReplication_AcknowledgeEvent_FullMethodName      = "/razpravljalnica.ChainReplication/AcknowledgeEvent"
	ChainReplication_GetLastSequenceNumber_FullMethodName = "/razpravljalnica.ChainReplication/GetLastSequenceNumber"
)

// ChainReplicationClient is the client API for ChainReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainReplicationClient interface {
	// Replicate an event to the next node in the chain (succeeeds when new node receives)
	ReplicateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Acknowledge the event with given sequence number was applied by the TAIL
	// (used for propagating ACKs back to HEAD)
	AcknowledgeEvent(ctx context.Context, in *AcknowledgeEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Ask the node for its latest sequence number
	GetLastSequenceNumber(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LastSequenceNumberResponse, error)
}

type chainReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewChainReplicationClient(cc grpc.ClientConnInterface) ChainReplicationClient {
	return &chainReplicationClient{cc}
}

func (c *chainReplicationClient) ReplicateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChainReplication_ReplicateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainReplicationClient) AcknowledgeEvent(ctx context.Context, in *AcknowledgeEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChainReplication_AcknowledgeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainReplicationClient) GetLastSequenceNumber(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LastSequenceNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastSequenceNumberResponse)
	err := c.cc.Invoke(ctx, ChainReplication_GetLastSequenceNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainReplicationServer is the server API for ChainReplication service.
// All implementations must embed UnimplementedChainReplicationServer
// for forward compatibility.
type ChainReplicationServer interface {
	// Replicate an event to the next node in the chain (succeeeds when new node receives)
	ReplicateEvent(context.Context, *Event) (*emptypb.Empty, error)
	// Acknowledge the event with given sequence number was applied by the TAIL
	// (used for propagating ACKs back to HEAD)
	AcknowledgeEvent(context.Context, *AcknowledgeEventRequest) (*emptypb.Empty, error)
	// Ask the node for its latest sequence number
	GetLastSequenceNumber(context.Context, *emptypb.Empty) (*LastSequenceNumberResponse, error)
	mustEmbedUnimplementedChainReplicationServer()
}

// UnimplementedChainReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainReplicationServer struct{}

func (UnimplementedChainReplicationServer) ReplicateEvent(context.Context, *Event) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateEvent not implemented")
}
func (UnimplementedChainReplicationServer) AcknowledgeEvent(context.Context, *AcknowledgeEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeEvent not implemented")
}
func (UnimplementedChainReplicationServer) GetLastSequenceNumber(context.Context, *emptypb.Empty) (*LastSequenceNumberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastSequenceNumber not implemented")
}
func (UnimplementedChainReplicationServer) mustEmbedUnimplementedChainReplicationServer() {}
func (UnimplementedChainReplicationServer) testEmbeddedByValue()                          {}

// UnsafeChainReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainReplicationServer will
// result in compilation errors.
type UnsafeChainReplicationServer interface {
	mustEmbedUnimplementedChainReplicationServer()
}

func RegisterChainReplicationServer(s grpc.ServiceRegistrar, srv ChainReplicationServer) {
	// If the following call panics, it indicates UnimplementedChainReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainReplication_ServiceDesc, srv)
}

func _ChainReplication_ReplicateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReplicationServer).ReplicateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainReplication_ReplicateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReplicationServer).ReplicateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainReplication_AcknowledgeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReplicationServer).AcknowledgeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainReplication_AcknowledgeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReplicationServer).AcknowledgeEvent(ctx, req.(*AcknowledgeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainReplication_GetLastSequenceNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReplicationServer).GetLastSequenceNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainReplication_GetLastSequenceNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReplicationServer).GetLastSequenceNumber(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainReplication_ServiceDesc is the grpc.ServiceDesc for ChainReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.ChainReplication",
	HandlerType: (*ChainReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicateEvent",
			Handler:    _ChainReplication_ReplicateEvent_Handler,
		},
		{
			MethodName: "AcknowledgeEvent",
			Handler:    _ChainReplication_AcknowledgeEvent_Handler,
		},
		{
			MethodName: "GetLastSequenceNumber",
			Handler:    _ChainReplication_GetLastSequenceNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "razpravljalnica.proto",
}
